#! /bin/bash

# Exit if any subcommand fails
set -e
set -o pipefail

# Precompile tasks if not in production and not in CI
# Also allow skipping precompilation with an ENV var
if [ "$LUCKY_ENV" != "production" ] && [ -z "$CI" ] && [ -z "$SKIP_LUCKY_TASK_PRECOMPILATION" ]; then
    shards build && \
    mkdir -p ../../bin && \
    cp -r $(pwd)/bin $(pwd)/../..
fi
